name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        browsers: [chrome, firefox, edge]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run in ${{ matrix.browsers }}
        uses: cypress-io/github-action@v6
        with:
          build: echo "skip build"
          start: echo "skip start"
          wait-on: "https://b-tkacz.github.io"
          wait-on-timeout: 120
          with:
          browser: ${{ matrix.browsers }}
          command: npx cypress run --browser ${{ matrix.browsers }} --reporter-options reportDir=cypress/reports/${{ matrix.browsers }}

      - name: Merge Mochawesome Reports
        run: npx mochawesome-merge cypress/reports/${{ matrix.browsers}}/*.json > cypress/reports/${{ matrix.browsers}}/merged-report.json

      - name: Generate Mochawesome HTML Report
        run: npx marge cypress/reports/${{ matrix.browsers}}/merged-report.json --reportDir cypress/reports/${{ matrix.browsers}} -f "${{ matrix.browsers}}--report.html"

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: Cypress HTML Report ${{ matrix.browsers }}
          path: cypress/reports/${{ matrix.browsers}}
